In [9]:
def metodo_euler(ecuacion_diferencial, a, b, h, condicion_inicial):
    """
    Implementacion del metodo de Euler para resolver ecuaciones diferenciales de primer orden.

    Parametros:
        ecuacion_diferencial : funcion f(t, y) que representa la ecuacion diferencial
        condicion_inicial: valor inicial y(t0)
        a : limite inferior del intervalo
        b : limite superior del intervalo
        h : Espaciamiento para generar los valores de t 
        condicion_inicial: valor inicial y(t0)
        
    Retorna:
        tiempos (list): lista de tiempos t
        valores (list): lista de soluciones y(t)
    """

# Calcular número de pasos (convertido a entero)
    n = int((b - a) / h)

    valores = [condicion_inicial]
    
    for i in range(n):
        y = valores[i] + h * ecuacion_diferencial(a + i*h, valores[i])
        valores.append(y)

    return valores

![Texto alternativo](imagenes/WhatsApp%20Image%202025-05-15%20at%2012.29.26%20PM.jpeg)


In [10]:
import numpy as np

f = lambda t,y : t*np.exp(3*t)-2*y
metodo_euler(f, 0, 1, 0.25, 0)

[0,
 np.float64(0.0),
 np.float64(0.13231250103829217),
 np.float64(0.6263673843114042),
 np.float64(2.092134161472926)]

![Texto alternativo](imagenes/)

In [11]:
def f(t, u):
    """
    Cambia la ecuacion diferencial

    u = arreglo de variables u = [w,z] es decir que f(t, [w,z])

    """

    w = u[0]
    z = u[1]
    n = len(u)
    y = np.zeros(n)
    y[0] = z # Ecuacion 1
    y[1] = t * np.exp(t)-t+2*z-w
    return y

In [12]:
metodo_euler(f, 0, 1, 0.25, [0,0])

[[0, 0],
 array([0., 0.]),
 array([0.        , 0.01775159]),
 array([0.0044379 , 0.10771754]),
 array([0.03136728, 0.36990434])]